### PR TITLE
Feature.clearjobsatstarup

### PR DESCRIPTION
**Pull request by indy-independence**
Reset jobs that are in state RUNNING or SCHEDULED (with scheduled_time in the past) to state ABORTED on API startup
Add ABORTED state to jobstatus Enum (required manual ALTER line in alembic revision file, but seems to be working)

Example output:
(cnaas-nms) [johanmarcusson@indy-x1 src]$ python3 -m cnaas_nms.run
[2019-12-09 15:35:50,698] INFO in scheduler: Scheduler started from filename cnaas_nms/run.py function get_app (API mode)
[2019-12-09 15:35:50,701] INFO in scheduler: Scheduler started with persistent jobstore, 10 threads
[2019-12-09 15:35:50,799] WARNING in job: Job found in unfinished RUNNING state at startup moved to ABORTED, id: 30
[2019-12-09 15:35:50,802] WARNING in job: Job found in past SCHEDULED state at startup moved to ABORTED, id: 2

### CODE REVIEW

**Comment by krihal** [comment]
Can we also sort the jobs? It's a bit confusing when the jobs are not in natural order.

**Comment by indy-independence** [comment]
> Can we also sort the jobs? It's a bit confusing when the jobs are not in natural order.

Sort the jobs in the database at startup? I think we can just try adding some default sort on the GET /devices API call instead

**Comment by krihal** [comment]
Can't see why we'd have to sort what is in the DB, I'd be happy enough if the result from GET is sorted.

**Comment by indy-independence** [comment]
Yes ok great, then I think we should fix it in another branch

**Pull request merged**
