### PR TITLE
Represent stack members in the data model

### PR DESCRIPTION
**Pull request by katsel**
Uninett would like to introduce the concept of a stack to cnaas-nms. This concept is also called "virtual chassis" by some vendors.

The goal is to keep implementation as vendor-agnostic as possible.

In the context of stacks, a "device" as seen by cnaas-nms is a virtual device that consists of 2 or more physical devices that logically function as one. These are called the "stack members".

We add a new class (or database table) called *stack member* that creates a mapping between
- serial number (or logical identifier) and
- stack position (or physical identifier)

for each member of a stack. It references the virtual device via its `device_id` (foreign key).

### CODE REVIEW

**Comment by indy-independence** [comment]
As someone mentioned earlier it seems like some vendors use MAC as identifier instead of serial number, maybe the name for this column could be "hardware_id" or something more generic?
Regarding priority values I'm not 100% sure you will actually need it to get things up and running, but at least for cisco and HP you can configure a value to influence which stack member will be the leader. For cisco values 1-15 and HP values 1-255
https://techhub.hpe.com/eginfolib/networking/docs/switches/WB/15-18/5998-8156_wb_2926_atmg/content/ch06s02.html
https://www.cisco.com/c/en/us/support/docs/switches/catalyst-3750-series-switches/71925-cat3750-create-switch-stks.html#anc10

**Comment by katsel** [comment]
## Consideration 1: Naming

The current (naive) implementation has a straight-forward naming of the fields for the use of Juniper equipment:
```python
    id = Column(Integer, autoincrement=True, primary_key=True)
    device_id = Column(Integer, ForeignKey('device.id'))
    serial = Column(String(64), nullable=False, unique=True)
    position = Column(Integer, nullable=False)
```
`serial` could be imprecise for some vendors, as remarked by @lunkwill42: they reference stack devices by mac address. The `String(64)` data type allows mac addresses -- so should the field should be named differently?

Similar things apply for `position`: Some vendors use letters (A, B, …) or labels to reference stack members.

Question is if this should be represented in the data model:
Having `position` as an integer provides obvious advantages like easy ordering and later re-use of the value (e.g. in templates) without any type checking or transformations.
A nullable "label" column could be additionally added.

@lunkwill42 suggested replacing `serial` with "logical ID" and `position` with "physical ID". While this is of course correct and the most generic way of naming the fields, I wonder about practicability in everyday networking life.
Any input is appreciated!

**Comment by katsel** [comment]
> As someone mentioned earlier it seems like some vendors use MAC as identifier instead of serial number, maybe the name for this column could be "hardware_id" or something more generic?

+1

> Regarding priority values I'm not 100% sure you will actually need it to get things up and running, but at least for cisco and HP you can configure a value to influence which stack member will be the leader. For cisco values 1-15 and HP values 1-255

Sounds like adding a nullable Integer priority field is a good idea.

**Comment by katsel** [comment]
Data model, revision 2:

- renamed "position" to "member_no" as the term member number is used consistently between vendors: Cisco, HP, Juniper
- made device_id not-nullable since stack members cannot exist without a matching device
- renamed "serial" to "hardware_id" to include the use of mac addresses as identifiers
- added a priority column. Priority values commonly run between 0 … 255.

**Comment by lunkwill42** [comment]
@katsel, I think you mixed these two up in the description:

> * serial number (or logical identifier) and
> 
> * stack position (or physical identifier)

And again:

> @lunkwill42 suggested replacing `serial` with "logical ID" and `position` with "physical ID". While this is of course correct and the most generic way of naming the fields, I wonder about practicability in everyday networking life.
> Any input is appreciated!

I did not. You have them mixed up. Serial is the physical id, position is the logical ID :-)



Other than that, I also give +1 to naming the field `hardware_id`.

Some background for @indy-independence that is missing from this PR (but may have been communicated elsewhere):

For Juniper VCs, before configuration, members will be numbered in the order of their first boot-up. The master will always be the first device to be powered on, but this can, of course, be changed later. However, for our CNaaS deployments, these restrictions apply:

1. We want to be able to specifically number the stack members in the order in which they are physically installed in the rack, as this makes it easier to identify the hardware correctly on-site. However, since we do not have 100% control of the order in which the devices are powered up the first time, the initial member numbers do not necessarily match this scheme.
2. When first installed, only the master stack member is patched with an actual uplink. The local hands&feet are instructed to always boot this device first. If not, a stack member without a physical uplink will be promoted to stack master, and we will not be able to reach the stack over the network. If this happens, we are SOL and cannot use either CLI or CNaaS-NMS to configure it. We would need the local hands&feet to install a console cable to be able to reconfigure the stack.

So, in essence, we will likely never need to use CNaaS-NMS to specify which member should become the master (at least not for Juniper). But it would be nice for CNaaS-NMS to tell which one is currently the master.

**Review by lunkwill42 — COMMENTED** [review]
The changes look short and sweet to me. Don't know SQLAlchemy and Alembic all that well, so I expect @indy-independence to conduct a more in-depth review :)

**Comment by katsel** [comment]
This PR includes

- the finalised data model for stack members
- methods on device to test if a device is a stack (=it has stack member/s) and to retrieve its stackmember/s
- unit tests for creating stack members assigned to a device, and for both methods

I also rewrote most of the device unit tests because they had side effects (left test data in the "real" database in case of failing tests), depended on a particular running order, or had no asserts in them.
@stveit and I added a function for an SQL test session that does not `commit()` any transactions to the database, but just uses `flush()` and will automatically rollback after the test has run, leaving the database unchanged.
This works well enough with SQLAlchemy. A more sustainable solution would be either using a test database on postgres (that is dismissed after the tests are run), using a completely independent in-memory database instance for testing purposes, or using mocks.
The [Essential SQLAlchemy](https://www.oreilly.com/library/view/essential-sqlalchemy-2nd/9781491916544/ch04.html) book has some ideas and inspirations.

**Comment by stveit** [comment]
Updates:

- Adds a test session that uses a sqlite in-memory database. As Sqlite does not support JSONB, fields with JSONB was changes to JsonType.
- test session used for db device tests. Tests are generally more cleaned up.
- adds is_stack field to the Device model used for defining if a device is a stack or not. Previously the idea was to check if a device was a stack by seeing if it has any stackmembers, but as it is valid for a stack to not have nay stackmembers defined, an explicit approach might be more helpful

**Comment by indy-independence** [comment]
> Updates:
> 
>     * Adds a test session that uses a sqlite in-memory database. As Sqlite does not support JSONB, fields with JSONB was changes to JsonType.

Why the need for sqlite in-memory database? Changing datatypes from JSONB to JsonType in currently deployed installations sounds like a huge risk.

> 
>     * test session used for db device tests. Tests are generally more cleaned up.
> 
>     * adds is_stack field to the Device model used for defining if a device is a stack or not. Previously the idea was to check if a device was a stack by seeing if it has any stackmembers, but as it is valid for a stack to not have nay stackmembers defined, an explicit approach might be more helpful

Even if it's valid to have a stack without any members, I don't see how this affects determining if a device is part of a stack or not by checking membership? Still seems unnecessary with an extra field.

**Comment by stveit** [comment]
> Why the need for sqlite in-memory database? Changing datatypes from JSONB to JsonType in currently deployed installations sounds like a huge risk.

The dream was to be able to run tests without needed a local postgresql database running. As far as I'm able to figure out, doing pretty much anything with the sqlalchemy models require a session, and a session seems to require a database to connect to. So an in-memory database is very useful for this. But yes, the big issue is the data type. It seems that you can in Alembic convert existing data to the new datatype, so it might not be impossible to do this safely. And I agree that it is drastic to change a datatype for this, so i am curious if you guys have better ways for running such tests :). I have been experimenting with testcontainers for spinning up a postgresql+redis database during tests as well, but this does make the tests a lot slower.

>Even if it's valid to have a stack without any members, I don't see how this affects determining if a device is part of a stack or not by checking membership? Still seems unnecessary with an extra field.

Hopefully I've understood this issue myself, so I'll try to explain it the best i can.

The stack itself is defined as a device, and the switches the stack consists of are not configured in cnaas-nms as devices, they are instead configured as stackmembers. So what we want to know is if a Device is in fact a stack or not. Specifically, this is something we want to know for the redundant uplink thingy, where a stack should be treated differently in this regard.
Then the question is, how to know if a device is a stack? A normal device that is not a stack will have no stackmembers. A device that is a stack, but where the stackmembers are not defined, will also have no stackmembers. So as I see it, only checking for whether or not stackmembers exist can lead you to mistake a Stack for a normal switch.

And what i mean here by "not having stackmembers defined" is not that the stack doesnt consist of several switches, but that the network admins using cnaas-nms might not have any need to map serialnumbers to stack position. If no stackmembers are defined, the stack will still work by selecting these values itself.

Hopefully there is some sense in what I've written, and I appreciate the quick feedback :)

**Comment by indy-independence** [comment]
> The dream was to be able to run tests without needed a local postgresql database running. As far as I'm able to figure out, doing pretty much anything with the sqlalchemy models require a session, and a session seems to require a database to connect to. So an in-memory database is very useful for this. But yes, the big issue is the data type. It seems that you can in Alembic convert existing data to the new datatype, so it might not be impossible to do this safely. And I agree that it is drastic to change a datatype for this, so i am curious if you guys have better ways for running such tests :). I have been experimenting with testcontainers for spinning up a postgresql+redis database during tests as well, but this does make the tests a lot slower.

Maybe you can keep the postgresql+redis containers running continuously if you want to be able to run rapid unit tests in some sort of debugging session for example? But yeah I think many things will require them.


> And what i mean here by "not having stackmembers defined" is not that the stack doesnt consist of several switches, but that the network admins using cnaas-nms might not have any need to map serialnumbers to stack position. If no stackmembers are defined, the stack will still work by selecting these values itself.

I would think it's better to always have the members and serial numbers for stack members saved even if you don't care about the ordering, and then just allow having member_no as value -1 or something if you don't care about the order. Maybe it's even possible to get the "naturally" selected member_no order from the switch when it boots up and save that if you don't want to set anything explicit. Hopefully all the serial numbers etc will be populated during ZTP anyhow so it's not any work needed to add them manually.

> Hopefully there is some sense in what I've written, and I appreciate the quick feedback :)

Yes it makes sense now, thanks for explaining :)

**Comment by stveit** [comment]
Updates:

- Revert sqlite in-memory stuff, but keeps the test_session that never commits as this is still useful (alternatively a method for wiping the postgresql db can be used)
- Revert is_stack changes.
- member_no nullable. This is from what you proposed of defining stackmembers without caring about positioning. If you dont care, let it be null.
- Change to hardware_id uniqueness. As it is not invalid for several stacks to configure the same serialnumbers, it makes sense to only restrict the hardware_id to be unique within a stack. This allows you for instance to move a switch from one stack to another and having the position be configured on the new stack beforehand.

**Comment by hmpf** [comment]
>  * Change to hardware_id uniqueness. As it is not invalid for several stacks to configure the same serialnumbers, it makes sense to only restrict the hardware_id to be unique within a stack. This allows you for instance to move a switch from one stack to another and having the position be configured on the new stack beforehand.

Nice catch!

**Comment by stveit** [comment]
Are there any more changes I should do before this can get accepted @indy-independence ?

**Comment by indy-independence** [comment]
I did a last check with the team here and it seems like no one could foresee any more things to consider about the data model yet, so I'll merge this

**Pull request merged**
