### PR TITLE
Allow having two uplinks to stack

### PR DESCRIPTION
**Pull request by stveit**
As a stack is still a single device, multiple links between devices must be supported to be able to have two uplinks to a stack.
Draft changes trying to figure out what needs to be changed/what restrictions should there be to make this work properly.

current changes mostly change some code that assume one interface per neighbor into allowing multiple interfaces and removing any related restrictions.

### CODE REVIEW

**Comment by indy-independence** [comment]
The code looks nice! I did a few tests in our lab setup and it seems to work with manually adding a second link between a core and a dist device. I also ran a zerotouch/init of one dist switch and that still seems to be working.
I do think this branch has been forked from some old code though? Doesn't seem up to date with develop branch

**Comment by stveit** [comment]
Yeah i saw that it was behind a lot, i mistakenly branched off the wrong thing. I've rebased on develop now. do you mind if i force push it here, or should i make a new PR to avoid rebasing shared code?

**Comment by indy-independence** [comment]
Should be fine with a force push, I'm confident no one else from here did changes in this feature branch

**Comment by stveit** [comment]
And nice that it seems to work, I still havent tried using the lab here so im not entirely ready to be running tests, ill have to spend some time figuring it out

**Comment by indy-independence** [comment]
Work continued in PR #270 , closing this

**Pull request closed without merging**
