### PR TITLE
Uninett/Docker again!

### PR DESCRIPTION
**Pull request by katsel**
In summary, I have
- reduced the number of layers on the Dockerfiles
- updated the shell scripts a bit
- run `hadolint` against Dockerfiles, `shellcheck` against shell scripts, and fixed the most obvious things that came up
- removed some lingering old config.

Please see the commit messages for more details.

I haven't tested this against our lab setup, but will do during the course of the day. None of this should break anything, but please examine thoroughly before merging and/or using in prod.

I left atomic logical commits intact for easier review, can rebase if that's desired.

### CODE REVIEW

**Review by indy-independence — COMMENTED** [review]
The script is referred to in the uwsgi config, but I don't think it's "part of" the uwsgi config

**Comment by katsel** [comment]
@indy-independence 
I see.
The underlying idea: Keep any scripts that are not directly run by Docker during the build step out of the docker/ directory, and move them to `conf/`.

In general, are you okay with the script being located in `conf/`? In that case, I'd just change the commit message to something more accurate.

**Comment by indy-independence** [comment]
Maybe you could create a scripts/ directory if you want to keep it from the main directory?

**Comment by katsel** [comment]
I considered that, but don't think it's worth the hassle. It raises the question why some *scripts* are in that dir and others (= those run by Docker) are not.

A compromise could be to rename `conf/` to `payload/` and put both the config files and scripts in there.
But then payload is not a common term, and that may cause confusion.

Upon closer inspection, there is no clear-cut distinction between configuration and other things. If we're being a bit generous here, a script that is referenced [by a config file](https://github.com/SUNET/cnaas-nms/blob/develop/docker/api/config/uwsgi.ini#L15) and ONLY by a config file, can be considered part of a server's configuration in the Dockerfile context.

It's not perfect but it's close enough.

**Comment by indy-independence** [comment]
It's quite a lot of different things going on here so maybe it's better to split it up in to more than one PR
1. Removing of old config files/config replacement for db in dhcp container. This could be merged right away I think
2. Reducing the number of layers in docker, seems like a good idea and could probably be merged after proper testing
3. Changes in cnaas-setup-branch and scripts used by test build. I don't feel like this change is very important, but it would require a lot of time to do manual testing of the build setup since it might break things in the build script that is not detected before merging (since the build scripts themselves will be changed after merging)
4.  Moving scripts in to the config/ directory, this I'm not sure I even agree is a good idea

**Comment by katsel** [comment]
That's okay, I can break it down a bit.

**Comment by katsel** [comment]
Oops, that was too soon.
Reopened until new PRs for all changes have been made.

**Comment by katsel** [comment]
New PRs:

1. dhcpd ↪️ #184

**Comment by katsel** [comment]
All changes live on other PRs now (see last comment). Closing this one.

**Pull request closed without merging**
